#!/bin/bash

# //define a name = check_name


check_even () {
    local mod=2
    echo "The value of mod is $mod inside of function"
    if [ $(("$1" % $mod)) -eq 0 ]
    then 
       echo "The number $1 is even!";
    else 
       echo "The number $1 is odd!"
    fi
}


number=20


check_even $number 
echo " The value of $mod is outside of function:"