#!/bin/bash

number=255454686789

if [ $((number % 2)) -eq 0 ];
then
   echo "The number $number is even!";
else 
   echo "The number $number is odd!"
fi


number=897984992

if [ $((number % 3)) -eq 0 ];
then 
      echo "This number $number is a multiple of 3";
else 
      echo "The number $number  is NOT a mutiple of 3";

      fi